### ISSUE TITLE
Help Explaining the Alg Behind The Node Positioning 

### ISSUE THREAD

**Issue by hero-clashes** [h4de5/godot-familytree#2]
So I am making a similar project for a family member, and I stumbled upon your code, the positions looks really goos, and I am wondering if you could explain how it works since I kinda got lost in the code
and Thanks in advance

**Comment by h4de5** [comment]
unfortunately I never got the positioning right. the plan was to put siblings to the side and place nephews at the same level as kids. but it was always overlapping. ended up buying pthe one time pro version from Ahnenblatt - they got that right.

**Comment by hero-clashes** [comment]
I see, thanks for the help anyway
